---

- name: create main user
  user:
    name: "{{ main_user }}"
    shell: /bin/zsh
    create_home: yes
    groups: "{{ user_groups }}"
    append: yes

- name: add main user to sudoers
  copy:
    dest: /etc/sudoers.d/{{ main_user }}-user
    content: |
      {{ main_user }} ALL=(ALL) ALL
    validate: 'visudo -csf %s'

- name: check exsistance of .ssh folder
  become_user: "{{ main_user }}"
  file:
    path: ~/.ssh
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: u+rwx,g-rwx,o-rwx #0700

- name: check SSH key presence
  become_user: "{{ main_user }}"
  stat:
    path: ~/.ssh/id_{{ main_user_key_type }}
  register: ssh_key_file

- name: generate SSH key
  become_user: "{{ main_user }}"
  openssh_keypair:
    path: ~/.ssh/id_{{ main_user_key_type }}
    type: "{{ main_user_key_type }}"
    comment: "{{ main_user }}-{{ ansible_date_time.year }}-{{ ansible_date_time.month }}@{{ inventory_hostname }}"
  when: not ssh_key_file.stat.exists

- name: init GPG
  become_user: "{{ main_user }}"
  command: gpg --list-keys
  when: not ansible_check_mode

- name: create home directories
  become_user: "{{ main_user }}"
  file:
    path: ~/{{ item }}
    state: directory
  loop: "{{ user_directories }}"

# Custom config 

# - import_tasks: dotfiles.yml