---

- name: update pacman cache
  pacman:
    update_cache: yes

- name: test install AUR packages
  yay:
    name: cheat-bin
    state: present
  ignore_errors: yes

# - name: install packages
#   yay:
#     name: "{{ item }}"
#     state: present
#   loop: "{{ system_packages + additional_packages|default([]) }}"
#   ignore_errors: yes